name: Deploy Pupilens + Kero Ótica Landing Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload Pupilens + Kero Ótica to DreamHost (SSH)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy Pupilens + Kero Ótica via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "pupilens_and_kero_otica_LP/*"
          target: "/home/deploy_LPs/pupilens-kero.com/lp-pupilens-kero-otica" 
